-- Migration 407: AI Support Comments for Feedback System
-- ─────────────────────────────────────────────────────────
-- Creates the feedback_comments table and adds ai reply support
-- to both feedback_reports and beta_feedback tables.

-- ─── 1. Create feedback_comments table ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS feedback_comments (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  report_id    uuid NOT NULL,          -- FK to feedback_reports OR beta_feedback
  author_id    uuid REFERENCES profiles(id) ON DELETE SET NULL,  -- null = AI/system
  content      text NOT NULL,
  is_internal  boolean DEFAULT false,  -- true = only admin sees
  is_ai_reply  boolean DEFAULT false,  -- true = generated by AI support engine
  ai_metadata  jsonb DEFAULT '{}'::jsonb, -- engine name, category, generatedAt
  mentioned_user_ids uuid[] DEFAULT '{}',
  created_at   timestamptz DEFAULT now()
);

-- ─── 2. Indexes ───────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_feedback_comments_report_id
  ON feedback_comments(report_id);

CREATE INDEX IF NOT EXISTS idx_feedback_comments_author_id
  ON feedback_comments(author_id);

CREATE INDEX IF NOT EXISTS idx_feedback_comments_is_ai_reply
  ON feedback_comments(is_ai_reply);

CREATE INDEX IF NOT EXISTS idx_feedback_comments_created_at
  ON feedback_comments(created_at DESC);

-- ─── 3. Enable RLS ────────────────────────────────────────────────────────────
ALTER TABLE feedback_comments ENABLE ROW LEVEL SECURITY;

-- Anyone who submitted the parent report can see public comments
CREATE POLICY "Users can view non-internal comments"
  ON feedback_comments FOR SELECT
  USING (is_internal = false);

-- Authenticated users can insert their own comments
CREATE POLICY "Authenticated users can add comments"
  ON feedback_comments FOR INSERT
  WITH CHECK (auth.uid() IS NULL OR author_id = auth.uid() OR author_id IS NULL);

-- Admins can see all (including internal)
CREATE POLICY "Admins can view all comments"
  ON feedback_comments FOR SELECT
  USING (
    auth.jwt() ->> 'role' = 'admin' OR
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- Admins can insert any comment (including AI replies with null author)
CREATE POLICY "Admins can insert any comment"
  ON feedback_comments FOR INSERT
  WITH CHECK (
    auth.jwt() ->> 'role' = 'admin' OR
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- ─── 4. Service role bypass (for server-side AI inserts) ─────────────────────
-- The server uses the service_role key which bypasses RLS automatically.
-- No additional policy needed.

-- ─── 5. Add ai_response column to beta_feedback ───────────────────────────────
-- Allows direct AI reply on beta_feedback submissions (non-report path)
ALTER TABLE beta_feedback 
  ADD COLUMN IF NOT EXISTS ai_response text,
  ADD COLUMN IF NOT EXISTS ai_responded_at timestamptz;
