export interface CurrencyConfig {
  code: string;
  name: string;
  symbol: string;
  flag: string;
  color: string;
  status: 'active' | 'coming_soon' | 'disabled';
  provider: string;
  features: string[];
  notice?: string;
  deposit_enabled: boolean;
  withdraw_enabled: boolean;
  transfer_enabled: boolean;
  buy_enabled: boolean;
  sell_enabled: boolean;
  convert_enabled: boolean;
  decimal_places: number;
  tooltip?: string;
}

export interface CryptoCurrencyConfig {
  code: string;
  name: string;
  symbol: string;
  flag: string;
  color: string;
  status: 'active' | 'coming_soon' | 'disabled';
  custodyStatus: 'coming_soon' | 'active';
  custodyBadgeText: string;
  deposit_enabled: boolean;
  withdraw_enabled: boolean;
  buy_enabled: boolean;
  sell_enabled: boolean;
  swap_enabled: boolean;
  decimal_places: number;
  networks: string[];
  tooltip?: string;
}

// ── FIAT CURRENCY CATALOG (Configuration-driven) ─────────────────────────────
// To unlock any currency in the future, simply change its `status` from 'coming_soon' to 'active'
// and set its feature flags to true!
export const FIAT_CURRENCY_CATALOG: CurrencyConfig[] = [
  // =========================================================================
  // ACTIVE FIAT CURRENCIES
  // =========================================================================
  {
    code: 'NGN',
    name: 'Nigerian Naira',
    symbol: '₦',
    flag: '🇳🇬',
    color: '#10b981',
    status: 'active',
    provider: 'Fincra Production',
    features: ['Deposit', 'Withdrawal', 'Bank Transfer', 'Virtual Account', 'Balance', 'Transaction History'],
    deposit_enabled: true,
    withdraw_enabled: true,
    transfer_enabled: true,
    buy_enabled: true,
    sell_enabled: true,
    convert_enabled: true,
    decimal_places: 2,
  },
  {
    code: 'USD',
    name: 'United States Dollar',
    symbol: '$',
    flag: '🇺🇸',
    color: '#3b82f6',
    status: 'active',
    provider: 'Fincra Merchant Wallet',
    features: ['Balance', 'Incoming international collections', 'FX conversion', 'Withdraw when merchant account is approved'],
    notice: 'Withdraw when merchant account is approved',
    deposit_enabled: true,
    withdraw_enabled: true,
    transfer_enabled: true,
    buy_enabled: true,
    sell_enabled: true,
    convert_enabled: true,
    decimal_places: 2,
  },
  {
    code: 'EUR',
    name: 'Euro',
    symbol: '€',
    flag: '🇪🇺',
    color: '#8b5cf6',
    status: 'active',
    provider: 'Fincra Merchant Wallet',
    features: ['Balance', 'Collections', 'FX conversion'],
    deposit_enabled: true,
    withdraw_enabled: true,
    transfer_enabled: true,
    buy_enabled: true,
    sell_enabled: true,
    convert_enabled: true,
    decimal_places: 2,
  },
  {
    code: 'GBP',
    name: 'British Pound',
    symbol: '£',
    flag: '🇬🇧',
    color: '#ec4899',
    status: 'active',
    provider: 'Fincra Merchant Wallet',
    features: ['Balance', 'Collections', 'FX conversion'],
    deposit_enabled: true,
    withdraw_enabled: true,
    transfer_enabled: true,
    buy_enabled: true,
    sell_enabled: true,
    convert_enabled: true,
    decimal_places: 2,
  },

  // =========================================================================
  // COMING SOON FIAT CURRENCIES
  // =========================================================================
  {
    code: 'CAD',
    name: 'Canadian Dollar',
    symbol: 'C$',
    flag: '🇨🇦',
    color: '#ff4d4d',
    status: 'coming_soon',
    provider: 'Banking Partner Integration',
    features: ['Balance', 'Collections', 'FX conversion'],
    deposit_enabled: false,
    withdraw_enabled: false,
    transfer_enabled: false,
    buy_enabled: false,
    sell_enabled: false,
    convert_enabled: false,
    decimal_places: 2,
    tooltip: 'Available after banking partner activation.',
  },
  {
    code: 'AUD',
    name: 'Australian Dollar',
    symbol: 'A$',
    flag: '🇦🇺',
    color: '#f59e0b',
    status: 'coming_soon',
    provider: 'Banking Partner Integration',
    features: ['Balance', 'Collections', 'FX conversion'],
    deposit_enabled: false,
    withdraw_enabled: false,
    transfer_enabled: false,
    buy_enabled: false,
    sell_enabled: false,
    convert_enabled: false,
    decimal_places: 2,
    tooltip: 'Available after banking partner activation.',
  },
  {
    code: 'NZD',
    name: 'New Zealand Dollar',
    symbol: 'NZ$',
    flag: '🇳🇿',
    color: '#00247d',
    status: 'coming_soon',
    provider: 'Banking Partner Integration',
    features: ['Balance', 'Collections', 'FX conversion'],
    deposit_enabled: false,
    withdraw_enabled: false,
    transfer_enabled: false,
    buy_enabled: false,
    sell_enabled: false,
    convert_enabled: false,
    decimal_places: 2,
    tooltip: 'Available after banking partner activation.',
  },
  {
    code: 'JPY',
    name: 'Japanese Yen',
    symbol: '¥',
    flag: '🇯🇵',
    color: '#bc002d',
    status: 'coming_soon',
    provider: 'Banking Partner Integration',
    features: ['Balance', 'Collections', 'FX conversion'],
    deposit_enabled: false,
    withdraw_enabled: false,
    transfer_enabled: false,
    buy_enabled: false,
    sell_enabled: false,
    convert_enabled: false,
    decimal_places: 0,
    tooltip: 'Available after banking partner activation.',
  },
  {
    code: 'GHS',
    name: 'Ghanaian Cedi',
    symbol: 'GH₵',
    flag: '🇬🇭',
    color: '#006b3f',
    status: 'coming_soon',
    provider: 'Banking Partner Integration',
    features: ['Balance', 'Collections', 'FX conversion'],
    deposit_enabled: false,
    withdraw_enabled: false,
    transfer_enabled: false,
    buy_enabled: false,
    sell_enabled: false,
    convert_enabled: false,
    decimal_places: 2,
    tooltip: 'Available after banking partner activation.',
  },
  {
    code: 'KES',
    name: 'Kenyan Shilling',
    symbol: 'KSh',
    flag: '🇰🇪',
    color: '#990000',
    status: 'coming_soon',
    provider: 'Banking Partner Integration',
    features: ['Balance', 'Collections', 'FX conversion'],
    deposit_enabled: false,
    withdraw_enabled: false,
    transfer_enabled: false,
    buy_enabled: false,
    sell_enabled: false,
    convert_enabled: false,
    decimal_places: 2,
    tooltip: 'Available after banking partner activation.',
  },
  {
    code: 'TZS',
    name: 'Tanzanian Shilling',
    symbol: 'TSh',
    flag: '🇹🇿',
    color: '#1ebf53',
    status: 'coming_soon',
    provider: 'Banking Partner Integration',
    features: ['Balance', 'Collections', 'FX conversion'],
    deposit_enabled: false,
    withdraw_enabled: false,
    transfer_enabled: false,
    buy_enabled: false,
    sell_enabled: false,
    convert_enabled: false,
    decimal_places: 2,
    tooltip: 'Available after banking partner activation.',
  },
  {
    code: 'UGX',
    name: 'Ugandan Shilling',
    symbol: 'USh',
    flag: '🇺🇬',
    color: '#fcdc04',
    status: 'coming_soon',
    provider: 'Banking Partner Integration',
    features: ['Balance', 'Collections', 'FX conversion'],
    deposit_enabled: false,
    withdraw_enabled: false,
    transfer_enabled: false,
    buy_enabled: false,
    sell_enabled: false,
    convert_enabled: false,
    decimal_places: 2,
    tooltip: 'Available after banking partner activation.',
  },
  {
    code: 'ZAR',
    name: 'South African Rand',
    symbol: 'R',
    flag: '🇿🇦',
    color: '#007749',
    status: 'coming_soon',
    provider: 'Banking Partner Integration',
    features: ['Balance', 'Collections', 'FX conversion'],
    deposit_enabled: false,
    withdraw_enabled: false,
    transfer_enabled: false,
    buy_enabled: false,
    sell_enabled: false,
    convert_enabled: false,
    decimal_places: 2,
    tooltip: 'Available after banking partner activation.',
  },
  {
    code: 'EGP',
    name: 'Egyptian Pound',
    symbol: 'E£',
    flag: '🇪🇬',
    color: '#c09300',
    status: 'coming_soon',
    provider: 'Banking Partner Integration',
    features: ['Balance', 'Collections', 'FX conversion'],
    deposit_enabled: false,
    withdraw_enabled: false,
    transfer_enabled: false,
    buy_enabled: false,
    sell_enabled: false,
    convert_enabled: false,
    decimal_places: 2,
    tooltip: 'Available after banking partner activation.',
  },
  {
    code: 'CNY',
    name: 'Chinese Yuan',
    symbol: '¥',
    flag: '🇨🇳',
    color: '#de2910',
    status: 'coming_soon',
    provider: 'Banking Partner Integration',
    features: ['Balance', 'Collections', 'FX conversion'],
    deposit_enabled: false,
    withdraw_enabled: false,
    transfer_enabled: false,
    buy_enabled: false,
    sell_enabled: false,
    convert_enabled: false,
    decimal_places: 2,
    tooltip: 'Available after banking partner activation.',
  },
  {
    code: 'CNH',
    name: 'Offshore Yuan',
    symbol: 'CNH¥',
    flag: '🇨🇳',
    color: '#ff4e00',
    status: 'coming_soon',
    provider: 'Banking Partner Integration',
    features: ['Balance', 'Collections', 'FX conversion'],
    deposit_enabled: false,
    withdraw_enabled: false,
    transfer_enabled: false,
    buy_enabled: false,
    sell_enabled: false,
    convert_enabled: false,
    decimal_places: 2,
    tooltip: 'Available after banking partner activation.',
  },
  {
    code: 'MWK',
    name: 'Malawian Kwacha',
    symbol: 'MK',
    flag: '🇲🇼',
    color: '#ea2328',
    status: 'coming_soon',
    provider: 'Banking Partner Integration',
    features: ['Balance', 'Collections', 'FX conversion'],
    deposit_enabled: false,
    withdraw_enabled: false,
    transfer_enabled: false,
    buy_enabled: false,
    sell_enabled: false,
    convert_enabled: false,
    decimal_places: 2,
    tooltip: 'Available after banking partner activation.',
  },
  {
    code: 'RWF',
    name: 'Rwandan Franc',
    symbol: 'FRw',
    flag: '🇷🇼',
    color: '#00a3e0',
    status: 'coming_soon',
    provider: 'Banking Partner Integration',
    features: ['Balance', 'Collections', 'FX conversion'],
    deposit_enabled: false,
    withdraw_enabled: false,
    transfer_enabled: false,
    buy_enabled: false,
    sell_enabled: false,
    convert_enabled: false,
    decimal_places: 2,
    tooltip: 'Available after banking partner activation.',
  },
  {
    code: 'ZMW',
    name: 'Zambian Kwacha',
    symbol: 'ZK',
    flag: '🇿🇲',
    color: '#198a00',
    status: 'coming_soon',
    provider: 'Banking Partner Integration',
    features: ['Balance', 'Collections', 'FX conversion'],
    deposit_enabled: false,
    withdraw_enabled: false,
    transfer_enabled: false,
    buy_enabled: false,
    sell_enabled: false,
    convert_enabled: false,
    decimal_places: 2,
    tooltip: 'Available after banking partner activation.',
  },
  {
    code: 'XOF',
    name: 'West African CFA Franc',
    symbol: 'CFA',
    flag: '🌍',
    color: '#008559',
    status: 'coming_soon',
    provider: 'Banking Partner Integration',
    features: ['Balance', 'Collections', 'FX conversion'],
    deposit_enabled: false,
    withdraw_enabled: false,
    transfer_enabled: false,
    buy_enabled: false,
    sell_enabled: false,
    convert_enabled: false,
    decimal_places: 0,
    tooltip: 'Available after banking partner activation.',
  },
  {
    code: 'XAF',
    name: 'Central African CFA Franc',
    symbol: 'FCFA',
    flag: '🌍',
    color: '#005b82',
    status: 'coming_soon',
    provider: 'Banking Partner Integration',
    features: ['Balance', 'Collections', 'FX conversion'],
    deposit_enabled: false,
    withdraw_enabled: false,
    transfer_enabled: false,
    buy_enabled: false,
    sell_enabled: false,
    convert_enabled: false,
    decimal_places: 0,
    tooltip: 'Available after banking partner activation.',
  },
];

// ── CRYPTO CURRENCY CATALOG ──────────────────────────────────────────────────
export const CRYPTO_CURRENCY_CATALOG: CryptoCurrencyConfig[] = [
  {
    code: 'BTC',
    name: 'Bitcoin',
    symbol: '₿',
    flag: '🟠',
    color: '#f59e0b',
    status: 'coming_soon',
    custodyStatus: 'coming_soon',
    custodyBadgeText: 'Custody Integration Coming Soon',
    deposit_enabled: false,
    withdraw_enabled: false,
    buy_enabled: false,
    sell_enabled: false,
    swap_enabled: false,
    decimal_places: 8,
    networks: ['bitcoin', 'BEP20'],
    tooltip: 'Custody integration coming soon until production custody is enabled.',
  },
  {
    code: 'ETH',
    name: 'Ethereum',
    symbol: 'Ξ',
    flag: '🔷',
    color: '#8b5cf6',
    status: 'coming_soon',
    custodyStatus: 'coming_soon',
    custodyBadgeText: 'Custody Integration Coming Soon',
    deposit_enabled: false,
    withdraw_enabled: false,
    buy_enabled: false,
    sell_enabled: false,
    swap_enabled: false,
    decimal_places: 6,
    networks: ['ERC20', 'BEP20'],
    tooltip: 'Custody integration coming soon until production custody is enabled.',
  },
  {
    code: 'USDT',
    name: 'Tether',
    symbol: '₮',
    flag: '🟢',
    color: '#26a17b',
    status: 'coming_soon',
    custodyStatus: 'coming_soon',
    custodyBadgeText: 'Custody Integration Coming Soon',
    deposit_enabled: false,
    withdraw_enabled: false,
    buy_enabled: false,
    sell_enabled: false,
    swap_enabled: false,
    decimal_places: 2,
    networks: ['TRC20', 'ERC20', 'BEP20'],
    tooltip: 'Custody integration coming soon until production custody is enabled.',
  },
  {
    code: 'USDC',
    name: 'USD Coin',
    symbol: '●',
    flag: '🔵',
    color: '#2775ca',
    status: 'coming_soon',
    custodyStatus: 'coming_soon',
    custodyBadgeText: 'Custody Integration Coming Soon',
    deposit_enabled: false,
    withdraw_enabled: false,
    buy_enabled: false,
    sell_enabled: false,
    swap_enabled: false,
    decimal_places: 2,
    networks: ['ERC20', 'BEP20'],
    tooltip: 'Custody integration coming soon until production custody is enabled.',
  },
];

// Helper functions for easy filtering
export const getActiveFiatCurrencies = (): CurrencyConfig[] => {
  return FIAT_CURRENCY_CATALOG.filter(c => c.status === 'active');
};

export const getComingSoonFiatCurrencies = (): CurrencyConfig[] => {
  return FIAT_CURRENCY_CATALOG.filter(c => c.status === 'coming_soon');
};
