/**
 * Strict Transaction State Machine for Enterprise Payouts
 * ────────────────────────────────────────────────────────
 * Enforces legal state transition sequences for financial safety.
 * Illegal state jumps (e.g. SUCCESSFUL -> PROCESSING or FAILED -> SUCCESSFUL without reconciliation) are strictly blocked.
 */

const WITHDRAWAL_STATES = Object.freeze({
  CREATED:                   "CREATED",
  VALIDATED:                 "VALIDATED",
  TREASURY_CHECK:            "TREASURY_CHECK",
  TREASURY_FUNDING_REQUIRED: "TREASURY_FUNDING_REQUIRED",
  TREASURY_SOURCE_RESERVED:  "TREASURY_SOURCE_RESERVED",
  FX_QUOTE_LOCKED:           "FX_QUOTE_LOCKED",
  CONVERSION_SUBMITTED:      "CONVERSION_SUBMITTED",
  CONVERSION_PROCESSING:     "CONVERSION_PROCESSING",
  CONVERSION_SETTLED:        "CONVERSION_SETTLED",
  PAYOUT_FUNDS_CONFIRMED:    "PAYOUT_FUNDS_CONFIRMED",
  TREASURY_INSUFFICIENT:     "TREASURY_INSUFFICIENT",
  QUOTE_EXPIRED:             "QUOTE_EXPIRED",
  CONVERSION_FAILED:         "CONVERSION_FAILED",
  CONVERSION_TIMEOUT:        "CONVERSION_TIMEOUT",
  RECONCILIATION_REQUIRED:   "RECONCILIATION_REQUIRED",
  RESERVED:                  "RESERVED",
  SENT_TO_PROVIDER:          "SENT_TO_PROVIDER",
  PROCESSING:                "PROCESSING",
  SUCCESSFUL:                "SUCCESSFUL",
  FAILED:                    "FAILED",
  REVERSED:                  "REVERSED",
  MANUAL_REVIEW:             "MANUAL_REVIEW",
  CANCELLED:                 "CANCELLED",
  REJECTED:                  "REJECTED",
});

const LEGAL_TRANSITIONS = Object.freeze({
  [WITHDRAWAL_STATES.CREATED]: [
    WITHDRAWAL_STATES.VALIDATED,
    WITHDRAWAL_STATES.FAILED,
    WITHDRAWAL_STATES.CANCELLED
  ],
  [WITHDRAWAL_STATES.VALIDATED]: [
    WITHDRAWAL_STATES.TREASURY_CHECK,
    WITHDRAWAL_STATES.RESERVED,
    WITHDRAWAL_STATES.MANUAL_REVIEW,
    WITHDRAWAL_STATES.FAILED,
    WITHDRAWAL_STATES.CANCELLED
  ],
  [WITHDRAWAL_STATES.TREASURY_CHECK]: [
    WITHDRAWAL_STATES.RESERVED,
    WITHDRAWAL_STATES.TREASURY_FUNDING_REQUIRED,
    WITHDRAWAL_STATES.TREASURY_INSUFFICIENT,
    WITHDRAWAL_STATES.FAILED,
    WITHDRAWAL_STATES.CANCELLED
  ],
  [WITHDRAWAL_STATES.TREASURY_FUNDING_REQUIRED]: [
    WITHDRAWAL_STATES.TREASURY_SOURCE_RESERVED,
    WITHDRAWAL_STATES.TREASURY_INSUFFICIENT,
    WITHDRAWAL_STATES.FAILED,
    WITHDRAWAL_STATES.CANCELLED
  ],
  [WITHDRAWAL_STATES.TREASURY_SOURCE_RESERVED]: [
    WITHDRAWAL_STATES.FX_QUOTE_LOCKED,
    WITHDRAWAL_STATES.CONVERSION_SUBMITTED,
    WITHDRAWAL_STATES.CONVERSION_SETTLED,
    WITHDRAWAL_STATES.PAYOUT_FUNDS_CONFIRMED,
    WITHDRAWAL_STATES.TREASURY_INSUFFICIENT,
    WITHDRAWAL_STATES.FAILED,
    WITHDRAWAL_STATES.CANCELLED
  ],
  [WITHDRAWAL_STATES.FX_QUOTE_LOCKED]: [
    WITHDRAWAL_STATES.CONVERSION_SUBMITTED,
    WITHDRAWAL_STATES.QUOTE_EXPIRED,
    WITHDRAWAL_STATES.FAILED,
    WITHDRAWAL_STATES.CANCELLED
  ],
  [WITHDRAWAL_STATES.QUOTE_EXPIRED]: [
    WITHDRAWAL_STATES.FX_QUOTE_LOCKED,
    WITHDRAWAL_STATES.FAILED,
    WITHDRAWAL_STATES.CANCELLED
  ],
  [WITHDRAWAL_STATES.CONVERSION_SUBMITTED]: [
    WITHDRAWAL_STATES.CONVERSION_PROCESSING,
    WITHDRAWAL_STATES.CONVERSION_SETTLED,
    WITHDRAWAL_STATES.CONVERSION_TIMEOUT,
    WITHDRAWAL_STATES.CONVERSION_FAILED,
    WITHDRAWAL_STATES.RECONCILIATION_REQUIRED,
    WITHDRAWAL_STATES.FAILED
  ],
  [WITHDRAWAL_STATES.CONVERSION_PROCESSING]: [
    WITHDRAWAL_STATES.CONVERSION_SETTLED,
    WITHDRAWAL_STATES.CONVERSION_TIMEOUT,
    WITHDRAWAL_STATES.CONVERSION_FAILED,
    WITHDRAWAL_STATES.RECONCILIATION_REQUIRED,
    WITHDRAWAL_STATES.FAILED
  ],
  [WITHDRAWAL_STATES.CONVERSION_TIMEOUT]: [
    WITHDRAWAL_STATES.CONVERSION_SETTLED,
    WITHDRAWAL_STATES.RECONCILIATION_REQUIRED,
    WITHDRAWAL_STATES.CONVERSION_FAILED,
    WITHDRAWAL_STATES.FAILED
  ],
  [WITHDRAWAL_STATES.CONVERSION_SETTLED]: [
    WITHDRAWAL_STATES.PAYOUT_FUNDS_CONFIRMED,
    WITHDRAWAL_STATES.RECONCILIATION_REQUIRED,
    WITHDRAWAL_STATES.FAILED
  ],
  [WITHDRAWAL_STATES.PAYOUT_FUNDS_CONFIRMED]: [
    WITHDRAWAL_STATES.RESERVED,
    WITHDRAWAL_STATES.SENT_TO_PROVIDER,
    WITHDRAWAL_STATES.FAILED,
    WITHDRAWAL_STATES.CANCELLED
  ],
  [WITHDRAWAL_STATES.RESERVED]: [
    WITHDRAWAL_STATES.SENT_TO_PROVIDER,
    WITHDRAWAL_STATES.MANUAL_REVIEW,
    WITHDRAWAL_STATES.FAILED,
    WITHDRAWAL_STATES.REVERSED,
    WITHDRAWAL_STATES.CANCELLED
  ],
  [WITHDRAWAL_STATES.SENT_TO_PROVIDER]: [
    WITHDRAWAL_STATES.PROCESSING,
    WITHDRAWAL_STATES.SUCCESSFUL,
    WITHDRAWAL_STATES.FAILED,
    WITHDRAWAL_STATES.REVERSED,
    WITHDRAWAL_STATES.RECONCILIATION_REQUIRED
  ],
  [WITHDRAWAL_STATES.PROCESSING]: [
    WITHDRAWAL_STATES.SUCCESSFUL,
    WITHDRAWAL_STATES.FAILED,
    WITHDRAWAL_STATES.REVERSED,
    WITHDRAWAL_STATES.MANUAL_REVIEW,
    WITHDRAWAL_STATES.RECONCILIATION_REQUIRED
  ],
  [WITHDRAWAL_STATES.MANUAL_REVIEW]: [
    WITHDRAWAL_STATES.RESERVED,
    WITHDRAWAL_STATES.SENT_TO_PROVIDER,
    WITHDRAWAL_STATES.REJECTED,
    WITHDRAWAL_STATES.CANCELLED,
    WITHDRAWAL_STATES.REVERSED,
    WITHDRAWAL_STATES.RECONCILIATION_REQUIRED
  ],
  [WITHDRAWAL_STATES.RECONCILIATION_REQUIRED]: [
    WITHDRAWAL_STATES.CONVERSION_SETTLED,
    WITHDRAWAL_STATES.SUCCESSFUL,
    WITHDRAWAL_STATES.FAILED,
    WITHDRAWAL_STATES.REVERSED,
    WITHDRAWAL_STATES.CANCELLED
  ],
  // Terminal States
  [WITHDRAWAL_STATES.SUCCESSFUL]:            [],
  [WITHDRAWAL_STATES.FAILED]:                [WITHDRAWAL_STATES.REVERSED, WITHDRAWAL_STATES.RECONCILIATION_REQUIRED],
  [WITHDRAWAL_STATES.REVERSED]:              [],
  [WITHDRAWAL_STATES.CANCELLED]:             [],
  [WITHDRAWAL_STATES.TREASURY_INSUFFICIENT]: [],
  [WITHDRAWAL_STATES.CONVERSION_FAILED]:     [WITHDRAWAL_STATES.RECONCILIATION_REQUIRED, WITHDRAWAL_STATES.REVERSED],
  [WITHDRAWAL_STATES.REJECTED]:              [],
});

class InvalidStateTransitionError extends Error {
  constructor(currentState, nextState) {
    super(`Invalid State Transition: Cannot transition transaction state from '${currentState}' to '${nextState}'`);
    this.name = "InvalidStateTransitionError";
    this.currentState = currentState;
    this.nextState = nextState;
  }
}

/**
 * Validates if a state transition is legal.
 * @param {string} currentState 
 * @param {string} nextState 
 * @returns {boolean}
 */
function canTransition(currentState, nextState) {
  if (currentState === nextState) return true; // No-op transition
  const allowed = LEGAL_TRANSITIONS[currentState] || [];
  return allowed.includes(nextState);
}

/**
 * Asserts a legal transition; throws InvalidStateTransitionError if illegal.
 * @param {string} currentState 
 * @param {string} nextState 
 */
function assertTransition(currentState, nextState) {
  if (!canTransition(currentState, nextState)) {
    throw new InvalidStateTransitionError(currentState, nextState);
  }
}

module.exports = {
  WITHDRAWAL_STATES,
  canTransition,
  assertTransition,
  InvalidStateTransitionError,
};
