const axios = require("axios");
const crypto = require("crypto");
const https = require("https");
const logger = require("../utils/logger");

const NOWPAYMENTS_API_KEY = process.env.NOWPAYMENTS_API_KEY;
const NOWPAYMENTS_IPN_SECRET = process.env.NOWPAYMENTS_IPN_SECRET;
let baseUrl = process.env.NOWPAYMENTS_BASE_URL || "https://api.nowpayments.io";

if (!baseUrl.includes("/v1")) {
  baseUrl = `${baseUrl.replace(/\/$/, "")}/v1`;
}

/**
 * Axios instance with fintech-grade defaults:
 * - Persistent connections to prevent socket hang-ups
 * - Strict timeout
 */
const nowpayments = axios.create({
  baseURL: baseUrl,
  headers: {
    "x-api-key": NOWPAYMENTS_API_KEY,
    "Content-Type": "application/json",
  },
  httpsAgent: new https.Agent({ keepAlive: true }),
  timeout: 30000,
});

/**
 * Create a NOWPayments payment (low-level call)
 */
exports.createNowPaymentsPayment = async (data) => {
  try {
    const payload = {
      price_amount: data.amount,
      price_currency: data.currency.toLowerCase(),
      pay_currency: data.payCurrency || "btc",
      ipn_callback_url: data.ipnCallbackUrl,
      order_id: data.orderId,
      order_description: data.orderDescription,
    };

    const response = await nowpayments.post("/payment", payload);

    return {
      payment_id: response.data.payment_id,
      pay_address: response.data.pay_address,
      payment_status: response.data.payment_status,
      pay_amount: response.data.pay_amount,
      checkout_url: response.data.invoice_url ||
        `https://nowpayments.io/payment/?iid=${response.data.payment_id}`,
    };
  } catch (error) {
    logger.error("NowPayments: Payment Creation Failed", {
      error: error.response?.data || error.message,
      orderId: data.orderId,
    });
    throw new Error(
      error.response?.data?.message || "Crypto gateway initialization failed",
    );
  }
};

/**
 * Get or create a NOWPayments deposit address for a user/asset combination.
 *
 * COMPLIANCE NOTE (License-Light Model):
 *  - Addresses are generated by NOWPayments — crypto custody belongs to NOWPayments, NOT the platform.
 *  - We store the payment_id so IPN webhooks can reconcile incoming deposits.
 *  - Existing 'active' addresses are reused to avoid unnecessary API calls.
 *
 * @param {string} userId    - Supabase user UUID
 * @param {string} asset     - 'BTC' | 'ETH' | 'USDT' | 'USDC'
 * @param {object} supabase  - Supabase client instance
 * @returns {{ address: string, asset: string, payment_id: string, pay_amount: number|null }}
 */
exports.getOrCreateDepositAddress = async (userId, asset, supabase) => {
  const upAsset = asset.toUpperCase();

  const payCurrencyMap = {
    BTC: "btc",
    ETH: "eth",
    USDT: "usdterc20",
    USDC: "usdcerc20",
  };

  const payCurrency = payCurrencyMap[upAsset];
  if (!payCurrency) {
    throw new Error(`Asset ${upAsset} is not supported for crypto deposit`);
  }

  // 1. Try to reuse existing active address
  const { data: existing, error: fetchError } = await supabase
    .from("nowpayments_deposit_addresses")
    .select("*")
    .eq("user_id", userId)
    .eq("asset", upAsset)
    .eq("status", "active")
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();

  if (fetchError) {
    logger.error(
      "[NowPayments] Error fetching existing deposit address:",
      fetchError.message,
    );
  }

  if (existing) {
    logger.info(
      `[NowPayments] Reusing active ${upAsset} address for user ${userId}`,
    );
    return {
      address: existing.address,
      asset: upAsset,
      payment_id: existing.payment_id,
      pay_amount: existing.pay_amount,
    };
  }

  // 2. No active address — request a new one from NOWPayments
  const orderId = `${userId}_${upAsset}_${Date.now()}`;
  const ipnCallbackUrl = process.env.NOWPAYMENTS_WEBHOOK_URL ||
    `${process.env.SERVER_URL}/api/webhooks/nowpayments`;

  logger.info(
    `[NowPayments] Creating new deposit address for user ${userId} / asset ${upAsset}`,
  );

  const payment = await exports.createNowPaymentsPayment({
    amount: 1, // Minimal placeholder price; real amounts are tracked via IPN
    currency: "usd",
    payCurrency,
    orderId,
    orderDescription: `${upAsset} Deposit — ${userId}`,
    ipnCallbackUrl,
  });

  if (!payment.pay_address) {
    throw new Error("NOWPayments did not return a deposit address");
  }

  // 3. Mark any old active row for this user/asset as 'superseded'
  const { error: updateError } = await supabase
    .from("nowpayments_deposit_addresses")
    .update({ status: "superseded" })
    .eq("user_id", userId)
    .eq("asset", upAsset)
    .eq("status", "active");

  if (updateError) {
    logger.warn(
      "[NowPayments] Could not mark old address as superseded:",
      updateError.message,
    );
  }

  // 4. Cache the new address
  const { error: insertError } = await supabase
    .from("nowpayments_deposit_addresses")
    .insert({
      user_id: userId,
      asset: upAsset,
      pay_currency: payCurrency,
      address: payment.pay_address,
      payment_id: String(payment.payment_id),
      pay_amount: payment.pay_amount || null,
      status: "active",
    });

  if (insertError) {
    // Non-fatal: still return the address even if caching fails
    logger.error(
      "[NowPayments] Failed to cache deposit address:",
      insertError.message,
    );
  }

  return {
    address: payment.pay_address,
    asset: upAsset,
    payment_id: String(payment.payment_id),
    pay_amount: payment.pay_amount || null,
  };
};

/**
 * Verify NOWPayments IPN Signature (HMAC-SHA512)
 * Steps: sort body keys alphabetically → JSON.stringify (no spaces) → HMAC-SHA512
 */
exports.verifyIPNSignature = (headers, body) => {
  try {
    const signature = headers["x-nowpayments-sig"];
    if (!signature || !NOWPAYMENTS_IPN_SECRET) {
      logger.warn("IPN Verification: Missing signature or secret");
      return false;
    }

    const orderedBody = Object.keys(body)
      .sort()
      .reduce((obj, key) => {
        obj[key] = body[key];
        return obj;
      }, {});

    const hmac = crypto.createHmac("sha512", NOWPAYMENTS_IPN_SECRET);
    const hash = hmac.update(JSON.stringify(orderedBody)).digest("hex");

    const isValid = hash === signature;
    if (!isValid) {
      logger.warn("IPN Verification: Invalid Signature Detected", {
        providedSig: signature.substring(0, 8),
        expectedHash: hash.substring(0, 8),
      });
    }

    return isValid;
  } catch (error) {
    logger.error("IPN Verification: Error during check", {
      error: error.message,
    });
    return false;
  }
};

/**
 * Get Payment Status by payment_id (Direct API Check)
 */
exports.getPaymentStatus = async (paymentId) => {
  try {
    const response = await nowpayments.get(`/payment/${paymentId}`);
    return response.data;
  } catch (error) {
    logger.error("NowPayments: Status Fetch Failed", {
      paymentId,
      error: error.response?.data || error.message,
    });
    throw error;
  }
};
