const axios = require("axios");
const crypto = require("crypto");
const https = require("https");
const logger = require("../utils/logger");

const NOWPAYMENTS_API_KEY = process.env.NOWPAYMENTS_API_KEY;
const NOWPAYMENTS_IPN_SECRET = process.env.NOWPAYMENTS_IPN_SECRET;
let baseUrl = process.env.NOWPAYMENTS_BASE_URL || "https://api.nowpayments.io";

if (!baseUrl.includes("/v1")) {
  baseUrl = `${baseUrl.replace(/\/$/, "")}/v1`;
}

/**
 * Axios instance with fintech-grade defaults:
 * - Persistent connections to prevent socket hang-ups
 * - Strict timeout
 */
const nowpayments = axios.create({
  baseURL: baseUrl,
  headers: {
    "x-api-key": NOWPAYMENTS_API_KEY,
    "Content-Type": "application/json",
  },
  httpsAgent: new https.Agent({ keepAlive: true }),
  timeout: 10000,
});

/**
 * Create a NOWPayments payment (low-level call)
 */
exports.createNowPaymentsPayment = async (data) => {
  try {
    const payload = {
      price_amount: data.amount,
      price_currency: data.currency.toLowerCase(),
      pay_currency: data.payCurrency || "btc",
      ipn_callback_url: data.ipnCallbackUrl,
      order_id: data.orderId,
      order_description: data.orderDescription,
    };

    const response = await nowpayments.post("/payment", payload);

    return {
      payment_id: response.data.payment_id,
      pay_address: response.data.pay_address,
      payment_status: response.data.payment_status,
      pay_amount: response.data.pay_amount,
      checkout_url: response.data.invoice_url ||
        `https://nowpayments.io/payment/?iid=${response.data.payment_id}`,
    };
  } catch (error) {
    logger.error("NowPayments: Payment Creation Failed", {
      error: error.response?.data || error.message,
      orderId: data.orderId,
    });
    throw new Error(
      error.response?.data?.message || "Crypto gateway initialization failed",
    );
  }
};

/**
 * Get or create a NOWPayments deposit address for a user/asset combination.
 *
 * COMPLIANCE NOTE (License-Light Model):
 *  - Addresses are generated by NOWPayments — crypto custody belongs to NOWPayments, NOT the platform.
 *  - We store the payment_id so IPN webhooks can reconcile incoming deposits.
 *  - Existing 'active' addresses are reused to avoid unnecessary API calls.
 *
 * @param {string} userId    - Supabase user UUID
 * @param {string} asset     - 'BTC' | 'ETH' | 'USDT' | 'USDC'
 * @param {object} supabase  - Supabase client instance
 * @returns {{ address: string, asset: string, payment_id: string, pay_amount: number|null }}
 */
exports.getOrCreateDepositAddress = async (
  userId,
  asset,
  network,
  supabase,
  forceNew = false,
) => {
  const upAsset = asset.toUpperCase();
  const upNetwork = (network || "").toUpperCase();

  const payCurrencyMap = {
    BTC_BITCOIN: "btc",
    BTC_NATIVE: "btc",
    ETH_ETHEREUM: "eth",
    ETH_NATIVE: "eth",
    USDT_ERC20: "usdterc20",
    USDT_TRC20: "usdttrc20",
    USDT_BEP20: "usdtbsc",
    USDT_NATIVE: "usdttrc20", // Default to TRC20 for native
    USDC_ERC20: "usdcerc20",
    USDC_POLYGON: "usdcmatictoken",
    USDC_NATIVE: "usdcerc20", // Default to ERC20 for native
  };

  // Construct lookup key.
  // We now handle NATIVE specifically in the map, so we just normalize it.
  const networkKey = upNetwork === "NATIVE" || !network
    ? (upAsset === "BTC"
      ? "BITCOIN"
      : upAsset === "ETH"
      ? "ETHEREUM"
      : upAsset === "USDT"
      ? "TRC20"
      : upAsset === "USDC"
      ? "ERC20"
      : upNetwork)
    : upNetwork;

  const lookupKey = `${upAsset}_${networkKey}`;

  const payCurrency = payCurrencyMap[lookupKey];
  if (!payCurrency) {
    throw new Error(
      `Asset ${upAsset} on network ${upNetwork} is not supported`,
    );
  }

  // 1. Try to reuse existing active address from cache table (Skip if forceNew)
  if (!forceNew) {
    const { data: existing, error: fetchError } = await supabase
      .from("nowpayments_deposit_addresses")
      .select("*")
      .eq("user_id", userId)
      .eq("asset", upAsset)
      .eq("status", "active")
      .order("created_at", { ascending: false })
      .limit(1)
      .maybeSingle();

    if (existing) {
    const MOCK_KEYWORDS = ["-", "dummy", "test", "mock", "address", "123456", "example"];
    const isMock = existing.address && MOCK_KEYWORDS.some(kw => existing.address.toLowerCase().includes(kw));

    if (!isMock) {
      logger.info(
        `[NowPayments] Reusing active ${upAsset} address for user ${userId}`,
      );
      return {
        address: existing.address,
        currency: upAsset,
        network: upNetwork,
        payment_id: existing.payment_id,
      };
    } else {
      logger.warn(`[NowPayments] Detected cached mock address for user ${userId}, requiring fresh generation.`);
    }
  }
  }

  // 2. No active address — request a new one from NOWPayments
  const orderId = `${userId}_${upAsset}_${upNetwork}_${Date.now()}`;
  const ipnCallbackUrl = process.env.NOWPAYMENTS_WEBHOOK_URL ||
    `${process.env.SERVER_URL}/api/webhooks/nowpayments`;

  const payment = await exports.createNowPaymentsPayment({
    amount: 100,
    currency: "usd",
    payCurrency,
    orderId,
    orderDescription: `${upAsset} (${upNetwork}) Deposit — ${userId}`,
    ipnCallbackUrl,
  });

  if (!payment.pay_address) {
    throw new Error("NOWPayments did not return a deposit address");
  }

  // 3. Mark old addresses as superseded
  await supabase
    .from("nowpayments_deposit_addresses")
    .update({ status: "superseded" })
    .eq("user_id", userId)
    .eq("asset", upAsset)
    .eq("status", "active");

  // 4. Cache the new address and UPDATE THE WALLET TABLE
  const [{ error: cacheError }, { error: walletError }] = await Promise.all([
    supabase.from("nowpayments_deposit_addresses").insert({
      user_id: userId,
      asset: upAsset,
      pay_currency: payCurrency,
      address: payment.pay_address,
      payment_id: String(payment.payment_id),
      status: "active",
    }),
    supabase.from("wallets_store").update({
      address: payment.pay_address,
      provider: "nowpayments",
      provider_reference: String(payment.payment_id),
    })
      .eq("user_id", userId)
      .eq("currency", upAsset)
      .ilike("network", upNetwork),
  ]);

  if (cacheError) {
    logger.error("[NowPayments] Cache Error:", cacheError.message);
  }
  if (walletError) {
    logger.error("[NowPayments] Wallet Update Error:", walletError.message);
  }

  return {
    address: payment.pay_address,
    currency: upAsset,
    network: upNetwork,
    payment_id: String(payment.payment_id),
  };
};

/**
 * Verify NOWPayments IPN Signature (HMAC-SHA512)
 * Steps: sort body keys alphabetically → JSON.stringify (no spaces) → HMAC-SHA512
 */
exports.verifyIPNSignature = (headers, body) => {
  try {
    const signature = headers["x-nowpayments-sig"];
    if (!signature || !NOWPAYMENTS_IPN_SECRET) {
      logger.warn("IPN Verification: Missing signature or secret");
      return false;
    }

    const orderedBody = Object.keys(body)
      .sort()
      .reduce((obj, key) => {
        obj[key] = body[key];
        return obj;
      }, {});

    const hmac = crypto.createHmac("sha512", NOWPAYMENTS_IPN_SECRET);
    const hash = hmac.update(JSON.stringify(orderedBody)).digest("hex");

    const isValid = hash === signature;
    if (!isValid) {
      logger.warn("IPN Verification: Invalid Signature Detected", {
        providedSig: signature.substring(0, 8),
        expectedHash: hash.substring(0, 8),
      });
    }

    return isValid;
  } catch (error) {
    logger.error("IPN Verification: Error during check", {
      error: error.message,
    });
    return false;
  }
};

/**
 * Get Payment Status by payment_id (Direct API Check)
 */
exports.getPaymentStatus = async (paymentId) => {
  try {
    const response = await nowpayments.get(`/payment/${paymentId}`);
    return response.data;
  } catch (error) {
    logger.error("NowPayments: Status Fetch Failed", {
      paymentId,
      error: error.response?.data || error.message,
    });
    throw error;
  }
};
/**
 * Get exchange estimate (Direct API Check)
 * GET /v1/estimate?amount={amount}&currency_from={from}&currency_to={to}
 */
exports.getExchangeEstimate = async (fromCurrency, toCurrency, amount = 1) => {
  try {
    const payCurrencyMap = {
      BTC_BITCOIN: "btc",
      ETH_ETHEREUM: "eth",
      USDT_ERC20: "usdterc20",
      USDT_TRC20: "usdttrc20",
      USDT_BEP20: "usdtbsc",
      USDC_ERC20: "usdcerc20",
      USDC_POLYGON: "usdcmatictoken",
    };

    // Helper to resolve ticker - expected input is "CURRENCY" or "CURRENCY_NETWORK"
    const resolveTicker = (ticker) => {
      const upTicker = ticker.toUpperCase();
      if (payCurrencyMap[upTicker]) return payCurrencyMap[upTicker];

      // Handle "BTC", "USD", etc.
      return ticker.toLowerCase();
    };

    const from = resolveTicker(fromCurrency);
    const to = resolveTicker(toCurrency);

    // NOWPayments estimate endpoint
    const response = await nowpayments.get(
      `/estimate?amount=${amount}&currency_from=${from}&currency_to=${to}`,
    );

    return {
      estimated_amount: response.data.estimated_amount,
      rate: response.data.estimated_amount / amount,
      from_currency: from,
      to_currency: to,
    };
  } catch (error) {
    logger.error("NowPayments: Estimate Fetch Failed", {
      fromCurrency,
      toCurrency,
      amount,
      error: error.response?.data || error.message,
    });
    // Do not return 1.0 here; let the caller decide fallback
    throw error;
  }
};
