const supabase = require('../config/database');
const crypto = require('crypto');

exports.issueCertificate = async (req, res, next) => {
  try {
    const { userId } = req.user;
    const { pathId } = req.body;

    // 1. Verify meaningful completion (≥80% and quiz taken)
    const { data: progress } = await supabase
      .from('user_path_completion')
      .select('completion_pct, path_title, level')
      .eq('user_id', userId)
      .eq('path_id', pathId)
      .maybeSingle();

    if (!progress || progress.completion_pct < 80) {
      return res.status(403).json({
        error: 'Certificate requires at least 80% path completion.',
        current_pct: progress?.completion_pct ?? 0
      });
    }

    // 2. Fetch learner, path, space, creator info
    const [learnerRes, pathRes] = await Promise.all([
      supabase.from('profiles').select('full_name, username').eq('id', userId).single(),
      supabase.from('learning_paths')
        .select('title, space_id, creator_id, community_spaces(name), profiles(full_name, username)')
        .eq('id', pathId)
        .single()
    ]);

    if (learnerRes.error || pathRes.error) throw learnerRes.error || pathRes.error;

    const learner = learnerRes.data;
    const path = pathRes.data;

    // 3. Prevent duplicate certificates for the same path+learner
    const { data: existing } = await supabase
      .from('certificates')
      .select('id, certificate_token')
      .eq('learner_id', userId)
      .eq('path_id', pathId)
      .maybeSingle();

    if (existing) {
      return res.json({ message: 'Certificate already issued.', certificate: existing });
    }

    // 4. Gather completion evidence
    const { data: sessions } = await supabase
      .from('learning_sessions')
      .select('time_spent_seconds, accuracy')
      .eq('user_id', userId);
    const totalMinutes = Math.round(
      (sessions ?? []).reduce((s, r) => s + (r.time_spent_seconds ?? 0), 0) / 60
    );
    const avgAccuracy = sessions?.length
      ? sessions.reduce((s, r) => s + (r.accuracy ?? 0), 0) / sessions.length
      : null;

    // 5. Issue certificate (token generated by DB default)
    const { data: cert, error: certError } = await supabase
      .from('certificates')
      .insert({
        learner_id: userId,
        learner_name: learner.full_name || learner.username,
        path_id: pathId,
        path_title: path.title,
        space_id: path.space_id,
        space_name: path.community_spaces?.name ?? 'NoteStandard',
        creator_id: path.creator_id,
        creator_name: path.profiles?.full_name || path.profiles?.username || 'NoteStandard',
        completion_pct: progress.completion_pct,
        final_quiz_score: avgAccuracy,
        time_spent_minutes: totalMinutes
      })
      .select()
      .single();

    if (certError) throw certError;

    res.status(201).json({ certificate: cert });
  } catch (err) {
    next(err);
  }
};

exports.verifyCertificate = async (req, res, next) => {
  try {
    const { token } = req.params;

    if (!token || token.length < 20) {
      return res.status(400).json({ valid: false, reason: 'Invalid token format.' });
    }

    const { data: cert, error } = await supabase
      .from('certificates')
      .select(`
        certificate_token, learner_name, path_title, space_name, creator_name,
        completion_pct, issued_at, expires_at, is_revoked, revoke_reason, verification_url
      `)
      .eq('certificate_token', token)
      .maybeSingle();

    if (error || !cert) {
      return res.status(404).json({ valid: false, reason: 'Certificate not found.' });
    }

    if (cert.is_revoked) {
      return res.json({ valid: false, reason: cert.revoke_reason || 'This certificate has been revoked.' });
    }

    if (cert.expires_at && new Date(cert.expires_at) < new Date()) {
      return res.json({ valid: false, reason: 'This certificate has expired.' });
    }

    res.json({ valid: true, certificate: cert });
  } catch (err) {
    next(err);
  }
};
