'use strict';
/**
 * AITreasuryMonitor.js
 * ====================
 * Rule-based AI treasury monitoring engine.
 * Generates natural-language insights from live treasury data.
 *
 * This is NOT an LLM call — insights are generated by a deterministic
 * rule engine that patterns financial metrics and produces human-readable
 * observations with severity, confidence, and recommendations.
 *
 * Insight types:
 *   LIQUIDITY_WARNING         — Provider balance < requested volume
 *   HEALTH_DEGRADATION        — Payout success rate < threshold
 *   LATENCY_SPIKE             — Provider latency doubled in last hour
 *   ROUTING_RECOMMENDATION    — Recommend provider switch
 *   RESERVE_DEFICIT           — Liabilities exceed assets
 *   CONCENTRATION_RISK        — >80% treasury in one provider
 *   FAILOVER_ACTIVATED        — Multiple failover events detected
 *   RECONCILIATION_DISCREPANCY — Ledger ≠ provider records
 *   SETTLEMENT_DELAY          — Settlements stuck in PENDING
 *   FORECAST_ALERT            — Deficit projected within 24h
 *   SLA_BREACH                — Provider below SLA target
 *
 * @module services/treasury/AITreasuryMonitor
 */

const supabase = require('../../config/database');
const logger   = require('../../utils/logger');

// Thresholds
const THRESHOLDS = {
  SUCCESS_RATE_WARN:       95,
  SUCCESS_RATE_CRITICAL:   90,
  LATENCY_SPIKE_MULTIPLE:  2.0,   // 2× baseline → spike
  CONCENTRATION_HIGH:      80,    // >80% in one provider → HIGH risk
  CONCENTRATION_MEDIUM:    60,
  RESERVE_WARN:           105,
  RESERVE_CRITICAL:       100,
  SETTLEMENT_DELAY_HOURS:  24,    // Settlements stuck > 24h
  FAILOVER_ALERT_COUNT:    3,     // ≥3 failovers in 1h → alert
};

const AITreasuryMonitor = {
  /**
   * Run all insight rules and persist results.
   * Called by TreasuryBalanceSyncWorker every cycle.
   */
  async run() {
    const generated = [];

    const rules = [
      this._checkReserveRatios,
      this._checkHealthDegradation,
      this._checkConcentrationRisk,
      this._checkSettlementDelays,
      this._checkFailoverEvents,
      this._checkForecastAlerts,
      this._checkLatencySpikes,
      this._checkCryptoHotWallets,
    ];

    for (const rule of rules) {
      try {
        const insights = await rule.call(this);
        if (insights && insights.length > 0) {
          generated.push(...insights);
        }
      } catch (err) {
        logger.warn(`[AIMonitor] Rule error: ${err.message}`);
      }
    }

    // Persist all generated insights
    if (generated.length > 0) {
      await supabase
        .from('treasury_insights')
        .insert(generated)
        .catch(e => logger.warn(`[AIMonitor] Persist failed: ${e.message}`));

      // Supersede stale insights of the same type + provider
      await this._supersedeDuplicates();
    }

    logger.info(`[AIMonitor] Generated ${generated.length} insights.`);
    return generated;
  },

  /**
   * Get active insights for dashboard.
   */
  async getActiveInsights(limit = 50) {
    const { data } = await supabase
      .from('treasury_insights')
      .select('*')
      .eq('status', 'ACTIVE')
      .gt('auto_expires_at', new Date().toISOString())
      .order('generated_at', { ascending: false })
      .limit(limit);
    return data || [];
  },

  // ── Rules ─────────────────────────────────────────────────────────────────────

  async _checkReserveRatios() {
    const { data: ratios } = await supabase
      .from('reserve_ratios')
      .select('*')
      .order('computed_at', { ascending: false })
      .limit(10);

    if (!ratios) return [];
    const insights = [];
    const seen = new Set();

    for (const r of ratios) {
      if (seen.has(r.currency)) continue;
      seen.add(r.currency);

      if (r.reserve_ratio < THRESHOLDS.RESERVE_CRITICAL) {
        insights.push(this._makeInsight({
          type:        'RESERVE_DEFICIT',
          severity:    'CRITICAL',
          currency:    r.currency,
          title:       `${r.currency} reserve ratio is CRITICAL: ${r.reserve_ratio.toFixed(2)}%`,
          body:        `Total ${r.currency} user liabilities exceed external reserves. Reserve ratio: ${r.reserve_ratio.toFixed(2)}%. Immediate action required to prevent withdrawal failure.`,
          recommendation: `Add ${r.currency} liquidity to at least one provider. Consider suspending non-critical withdrawals until resolved.`,
          amount:      r.total_liability - r.total_assets,
          confidence:  1.0,
        }));
      } else if (r.reserve_ratio < THRESHOLDS.RESERVE_WARN) {
        insights.push(this._makeInsight({
          type:        'RESERVE_DEFICIT',
          severity:    'WARNING',
          currency:    r.currency,
          title:       `${r.currency} reserve ratio is LOW: ${r.reserve_ratio.toFixed(2)}%`,
          body:        `${r.currency} reserve ratio (${r.reserve_ratio.toFixed(2)}%) is below the 105% warning threshold. Monitor closely.`,
          recommendation: `Review ${r.currency} provider balances and consider scheduling a rebalance.`,
          confidence:  0.95,
        }));
      }
    }

    return insights;
  },

  async _checkHealthDegradation() {
    const { data: scores } = await supabase
      .from('provider_health_scores')
      .select('provider, composite_score, success_rate_1h, circuit_state');

    if (!scores) return [];
    const insights = [];

    for (const s of scores) {
      if (s.circuit_state === 'OPEN') {
        insights.push(this._makeInsight({
          type:        'HEALTH_DEGRADATION',
          severity:    'CRITICAL',
          provider:    s.provider,
          title:       `${s.provider} circuit breaker is OPEN — provider excluded from routing`,
          body:        `${s.provider} has failed enough consecutive health probes to trigger the circuit breaker. All traffic has been rerouted to alternative providers.`,
          recommendation: `Investigate ${s.provider} API status. Circuit will enter HALF_OPEN for recovery after 30 seconds.`,
          confidence:  1.0,
        }));
      } else if (s.success_rate_1h < THRESHOLDS.SUCCESS_RATE_CRITICAL) {
        insights.push(this._makeInsight({
          type:        'HEALTH_DEGRADATION',
          severity:    'WARNING',
          provider:    s.provider,
          title:       `${s.provider} success rate has dropped to ${s.success_rate_1h.toFixed(1)}%`,
          body:        `${s.provider} payout/deposit success rate (${s.success_rate_1h.toFixed(1)}%) has fallen below ${THRESHOLDS.SUCCESS_RATE_CRITICAL}% in the last hour.`,
          recommendation: `Recommend routing ${this._inferCurrency(s.provider)} operations to a backup provider until ${s.provider} recovers.`,
          confidence:  0.90,
        }));
      }
    }

    return insights;
  },

  async _checkConcentrationRisk() {
    const { data: balances } = await supabase
      .from('treasury_provider_balances')
      .select('provider, currency, available_balance')
      .eq('sync_status', 'SUCCESS');

    if (!balances) return [];

    // Group by currency
    const byCurrency = {};
    for (const b of balances) {
      if (!byCurrency[b.currency]) byCurrency[b.currency] = [];
      byCurrency[b.currency].push({ provider: b.provider, amount: parseFloat(b.available_balance || 0) });
    }

    const insights = [];

    for (const [currency, providers] of Object.entries(byCurrency)) {
      const total = providers.reduce((s, p) => s + p.amount, 0);
      if (total === 0) continue;

      const maxProv = providers.reduce((m, p) => p.amount > m.amount ? p : m, providers[0]);
      const pct     = (maxProv.amount / total) * 100;

      if (pct > THRESHOLDS.CONCENTRATION_HIGH) {
        insights.push(this._makeInsight({
          type:        'CONCENTRATION_RISK',
          severity:    'WARNING',
          provider:    maxProv.provider,
          currency,
          title:       `${pct.toFixed(1)}% of ${currency} treasury is concentrated in ${maxProv.provider}`,
          body:        `${maxProv.provider} holds ${pct.toFixed(1)}% of all ${currency} external assets (${maxProv.amount.toFixed(2)} ${currency}). High concentration risk — if ${maxProv.provider} becomes unavailable, ${(pct - 20).toFixed(0)}% of liquidity is at risk.`,
          recommendation: `Consider rebalancing ${currency} assets across providers. Target: no single provider > 60%.`,
          confidence:  0.95,
        }));
      }
    }

    return insights;
  },

  async _checkSettlementDelays() {
    const cutoff = new Date(Date.now() - THRESHOLDS.SETTLEMENT_DELAY_HOURS * 60 * 60 * 1000).toISOString();
    const { data: stuckSettlements } = await supabase
      .from('settlement_positions')
      .select('provider, currency, count:id')
      .eq('settlement_stage', 'PENDING_SETTLEMENT')
      .lt('created_at', cutoff);

    if (!stuckSettlements || stuckSettlements.length === 0) return [];

    const insights = [];
    // Group by provider
    const byProvider = {};
    for (const s of stuckSettlements) {
      byProvider[s.provider] = (byProvider[s.provider] || 0) + 1;
    }

    for (const [provider, count] of Object.entries(byProvider)) {
      insights.push(this._makeInsight({
        type:        'SETTLEMENT_DELAY',
        severity:    'WARNING',
        provider,
        title:       `${count} ${provider} settlement(s) stuck in PENDING_SETTLEMENT for over ${THRESHOLDS.SETTLEMENT_DELAY_HOURS}h`,
        body:        `${count} settlements from ${provider} have been in PENDING_SETTLEMENT status for more than ${THRESHOLDS.SETTLEMENT_DELAY_HOURS} hours. This may indicate a provider-side delay or a missing webhook.`,
        recommendation: `Review ${provider} settlement dashboard. Check for webhook delivery failures or provider-side settlement holds.`,
        confidence:  0.85,
      }));
    }

    return insights;
  },

  async _checkFailoverEvents() {
    const since = new Date(Date.now() - 60 * 60 * 1000).toISOString();
    const { data: failovers } = await supabase
      .from('routing_decisions')
      .select('id, failover_from')
      .gt('failover_hop', 0)
      .gte('created_at', since);

    const count = failovers?.length || 0;
    if (count < THRESHOLDS.FAILOVER_ALERT_COUNT) return [];

    return [this._makeInsight({
      type:        'FAILOVER_ACTIVATED',
      severity:    count >= 10 ? 'CRITICAL' : 'WARNING',
      title:       `${count} automatic failover events in the last hour`,
      body:        `${count} payment routing decisions triggered automatic failover in the last 60 minutes. This indicates elevated provider instability.`,
      recommendation: 'Review provider health scores and consider proactively routing to a more stable provider.',
      confidence:  0.92,
    })];
  },

  async _checkForecastAlerts() {
    const { data: forecasts } = await supabase
      .from('treasury_forecasts')
      .select('*')
      .eq('forecast_horizon', '24H')
      .eq('is_deficit_forecast', true)
      .order('generated_at', { ascending: false })
      .limit(10);

    const insights = [];
    const seen     = new Set();

    for (const f of (forecasts || [])) {
      if (seen.has(f.currency)) continue;
      seen.add(f.currency);

      insights.push(this._makeInsight({
        type:        'FORECAST_ALERT',
        severity:    f.reserve_below_critical ? 'CRITICAL' : 'WARNING',
        currency:    f.currency,
        title:       `Deficit projected for ${f.currency} within 24 hours`,
        body:        `Current ${f.currency} reserve: ${f.current_balance.toFixed(0)}. Projected balance in 24h: ${f.projected_balance.toFixed(0)} (ratio: ${f.projected_reserve_ratio.toFixed(1)}%). Net movement: ${f.projected_deposits.toFixed(0)} deposits − ${f.projected_withdrawals.toFixed(0)} withdrawals.`,
        recommendation: `Add ${f.currency} liquidity or reduce withdrawal capacity before deficit occurs.`,
        amount:      f.projected_balance,
        confidence:  f.confidence,
      }));
    }

    return insights;
  },

  async _checkLatencySpikes() {
    // Compare current P95 vs. 1-hour average from history
    const { data: current } = await supabase
      .from('provider_health_scores')
      .select('provider, p95_latency_ms');

    const since = new Date(Date.now() - 60 * 60 * 1000).toISOString();
    const { data: history } = await supabase
      .from('provider_health_score_history')
      .select('provider, p95_latency_ms')
      .gte('captured_at', since);

    const insights = [];

    for (const c of (current || [])) {
      if (!c.p95_latency_ms) continue;

      const historyForProvider = (history || []).filter(h => h.provider === c.provider);
      if (historyForProvider.length < 2) continue;

      const avgHistorical = historyForProvider.reduce((s, h) => s + (h.p95_latency_ms || 0), 0) / historyForProvider.length;
      const multiple      = avgHistorical > 0 ? c.p95_latency_ms / avgHistorical : 1;

      if (multiple >= THRESHOLDS.LATENCY_SPIKE_MULTIPLE) {
        insights.push(this._makeInsight({
          type:        'LATENCY_SPIKE',
          severity:    multiple >= 4 ? 'CRITICAL' : 'WARNING',
          provider:    c.provider,
          title:       `${c.provider} API latency has spiked ${multiple.toFixed(1)}× above baseline`,
          body:        `${c.provider} P95 latency is now ${c.p95_latency_ms}ms vs. 1-hour baseline of ${avgHistorical.toFixed(0)}ms — a ${multiple.toFixed(1)}× increase. This may indicate provider degradation.`,
          recommendation: `Monitor ${c.provider} closely. If latency persists, consider reducing routing weight until it recovers.`,
          confidence:  0.88,
        }));
      }
    }

    return insights;
  },

  async _checkCryptoHotWallets() {
    const { data: thresholds } = await supabase
      .from('hot_wallet_thresholds')
      .select('*');

    if (!thresholds || thresholds.length === 0) return [];

    const CryptoWalletInventoryService = require('./CryptoWalletInventoryService');
    const summary = await CryptoWalletInventoryService.getInventorySummary();

    const insights = [];

    for (const t of thresholds) {
      const match = summary.find(
        s => s.currency === t.asset && (t.network === 'NATIVE' || s.network === t.network)
      );

      const hotBal = match ? match.hot : 0;
      const minBal = parseFloat(t.min_balance || 0);
      const targetBal = parseFloat(t.target_balance || 0);

      if (hotBal < minBal) {
        const topUpNeeded = targetBal - hotBal;
        insights.push(this._makeInsight({
          type:           'LIQUIDITY_WARNING',
          severity:       hotBal < (minBal * 0.5) ? 'CRITICAL' : 'WARNING',
          provider:       'nowpayments',
          currency:       t.asset,
          title:          `${t.asset} Hot Wallet balance (${hotBal}) is below minimum threshold (${minBal})`,
          body:           `${t.asset} hot wallet balance is currently ${hotBal} ${t.asset}, which is below the minimum threshold of ${minBal} ${t.asset}. Required target is ${targetBal} ${t.asset}.`,
          recommendation: t.rebalance_action || `Move ${topUpNeeded.toFixed(2)} ${t.asset} from Cold/Warm storage to Hot Wallet.`,
          amount:         topUpNeeded,
          confidence:     0.98,
        }));
      }
    }

    return insights;
  },

  // ── Helpers ───────────────────────────────────────────────────────────────────

  _makeInsight({ type, severity, title, body, recommendation, provider, currency, amount, confidence }) {
    return {
      insight_type:      type,
      severity:          severity || 'INFO',
      title,
      body,
      recommendation:    recommendation || null,
      affected_provider: provider || null,
      affected_currency: currency || null,
      affected_amount:   amount || null,
      confidence:        confidence || 0.80,
      status:            'ACTIVE',
      auto_expires_at:   new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
      generated_at:      new Date().toISOString(),
    };
  },

  _inferCurrency(provider) {
    const map = { fincra: 'NGN/USD', anchor: 'NGN', paystack: 'NGN', grey: 'USD/EUR/GBP', nowpayments: 'crypto' };
    return map[provider] || 'multi-currency';
  },

  async _supersedeDuplicates() {
    // Mark older ACTIVE insights of the same type + provider as SUPERSEDED
    const { data: actives } = await supabase
      .from('treasury_insights')
      .select('id, insight_type, affected_provider, affected_currency, generated_at')
      .eq('status', 'ACTIVE')
      .order('generated_at', { ascending: false });

    if (!actives || actives.length === 0) return;

    const seen     = new Set();
    const toSupersede = [];

    for (const ins of actives) {
      const key = `${ins.insight_type}:${ins.affected_provider || ''}:${ins.affected_currency || ''}`;
      if (seen.has(key)) {
        toSupersede.push(ins.id);
      } else {
        seen.add(key);
      }
    }

    if (toSupersede.length > 0) {
      await supabase
        .from('treasury_insights')
        .update({ status: 'SUPERSEDED' })
        .in('id', toSupersede)
        .catch(() => {});
    }
  },
};

module.exports = AITreasuryMonitor;
