import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  TouchableOpacity,
  StyleSheet,
  ScrollView,
  ActivityIndicator,
  Alert,
  Share,
  FlatList,
  Clipboard,
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import {
  Users,
  Award,
  Copy,
  Share2,
  ArrowLeft,
  DollarSign,
  TrendingUp,
  RefreshCw,
  Gift,
} from 'lucide-react-native';

const UsersIcon = Users as any;
const AwardIcon = Award as any;
const CopyIcon = Copy as any;
const Share2Icon = Share2 as any;
const ArrowLeftIcon = ArrowLeft as any;
const DollarSignIcon = DollarSign as any;
const TrendingUpIcon = TrendingUp as any;
const RefreshCwIcon = RefreshCw as any;
const GiftIcon = Gift as any;

import apiClient from '../../api/apiClient';
import { useAuth } from '../../context/AuthContext';

interface CommissionItem {
  id: string;
  amount: number;
  currency?: string;
  source_user?: string;
  created_at: string;
}

interface AffiliateStats {
  referral_code: string;
  referral_link: string;
  total_referrals: number;
  total_earned: number;
  currency: string;
  commissions: CommissionItem[];
}

interface AffiliateScreenProps {
  navigation: any;
}

export const AffiliateScreen: React.FC<AffiliateScreenProps> = ({ navigation }) => {
  const insets = useSafeAreaInsets();
  const { user } = useAuth();

  const [loading, setLoading] = useState(true);
  const [stats, setStats] = useState<AffiliateStats | null>(null);

  const fetchAffiliateStats = async () => {
    try {
      setLoading(true);
      const res = await apiClient.get('/wallet/affiliates/my-stats');
      if (res.data) {
        setStats({
          referral_code: res.data.referral_code || user?.username || 'CODE123',
          referral_link: res.data.referral_link || `https://app.notestandard.com/register?ref=${user?.username || 'CODE123'}`,
          total_referrals: res.data.total_referrals || 0,
          total_earned: Number(res.data.total_earned || 0),
          currency: res.data.currency || 'USD',
          commissions: res.data.commissions || [],
        });
      }
    } catch (err) {
      console.warn('[AffiliateScreen] Error loading stats:', err);
      setStats({
        referral_code: user?.username || 'CODE123',
        referral_link: `https://app.notestandard.com/register?ref=${user?.username || 'CODE123'}`,
        total_referrals: 0,
        total_earned: 0,
        currency: 'USD',
        commissions: [],
      });
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchAffiliateStats();
  }, []);

  const handleCopyCode = () => {
    if (!stats?.referral_code) return;
    Clipboard.setString(stats.referral_code);
    Alert.alert('Copied!', 'Referral code copied to clipboard.');
  };

  const handleCopyLink = () => {
    if (!stats?.referral_link) return;
    Clipboard.setString(stats.referral_link);
    Alert.alert('Copied!', 'Referral link copied to clipboard.');
  };

  const handleClaimCommission = async () => {
    try {
      const res = await apiClient.post('/wallet/affiliates/claim');
      if (res.data?.success) {
        Alert.alert('Claim Successful', `Claimed $${res.data.amount || 0} into your wallet.`);
        fetchAffiliateStats();
      } else {
        Alert.alert('Claim', res.data?.message || 'No pending commission to claim.');
      }
    } catch (err: any) {
      Alert.alert('Claim Error', err.response?.data?.error || 'Failed to claim commission.');
    }
  };

  return (
    <View style={styles.container}>
      {/* Header Bar */}
      <View style={[styles.header, { paddingTop: insets.top + 8 }]}>
        <TouchableOpacity style={styles.backBtn} onPress={() => navigation.goBack()}>
          <ArrowLeftIcon size={22} color="#FFFFFF" />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Affiliate & Referrals</Text>
        <TouchableOpacity style={styles.refreshBtn} onPress={fetchAffiliateStats} disabled={loading}>
          <RefreshCwIcon size={18} color="#FFFFFF" />
        </TouchableOpacity>
      </View>

      <ScrollView contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}>
        {/* Hero Banner */}
        <View style={styles.heroCard}>
          <View style={styles.heroTitleRow}>
            <GiftIcon size={24} color="#F59E0B" />
            <Text style={styles.heroTitle}>Invite Friends, Earn Lifetime Rewards</Text>
          </View>
          <Text style={styles.heroSub}>
            Earn up to 20% commission on transaction fees generated by users who register using your referral link or code.
          </Text>

          {/* Metrics Row */}
          <View style={styles.metricsRow}>
            <View style={styles.metricBox}>
              <UsersIcon size={20} color="#3B82F6" />
              <Text style={styles.metricValue}>{stats?.total_referrals || 0}</Text>
              <Text style={styles.metricLabel}>Total Referrals</Text>
            </View>

            <View style={styles.metricBox}>
              <DollarSignIcon size={20} color="#10B981" />
              <Text style={styles.metricValue}>${(stats?.total_earned || 0).toFixed(2)}</Text>
              <Text style={styles.metricLabel}>Earned Income</Text>
            </View>
          </View>
        </View>

        {loading ? (
          <View style={styles.loadingBox}>
            <ActivityIndicator size="large" color="#3B82F6" />
            <Text style={styles.loadingText}>Fetching affiliate stats...</Text>
          </View>
        ) : (
          <View style={styles.contentGrid}>
            {/* Referral Code & Link Box */}
            <View style={styles.sectionCard}>
              <Text style={styles.sectionTitle}>Your Referral Credentials</Text>

              {/* Referral Code Box */}
              <View style={styles.codeRow}>
                <View style={styles.codeTextContainer}>
                  <Text style={styles.codeLabel}>Referral Code</Text>
                  <Text style={styles.codeValue}>{stats?.referral_code}</Text>
                </View>
                <TouchableOpacity style={styles.copyBtn} onPress={handleCopyCode}>
                  <CopyIcon size={16} color="#FFFFFF" />
                  <Text style={styles.copyBtnText}>Copy</Text>
                </TouchableOpacity>
              </View>

              {/* Referral Link Box */}
              <View style={styles.linkRow}>
                <Text style={styles.linkText} numberOfLines={1}>
                  {stats?.referral_link}
                </Text>

                <View style={styles.linkActions}>
                  <TouchableOpacity style={styles.iconBtn} onPress={handleCopyLink}>
                    <CopyIcon size={16} color="#3B82F6" />
                  </TouchableOpacity>
                  <TouchableOpacity style={styles.shareBtn} onPress={handleShareLink}>
                    <Share2Icon size={16} color="#FFFFFF" />
                    <Text style={styles.shareBtnText}>Share</Text>
                  </TouchableOpacity>
                </View>
              </View>
            </View>

            {/* Commissions History Section */}
            <View style={styles.sectionCard}>
              <Text style={styles.sectionTitle}>Commission Payout History</Text>

              {stats?.commissions && stats.commissions.length > 0 ? (
                stats.commissions.map(c => (
                  <View key={c.id} style={styles.commissionRow}>
                    <View style={styles.commissionLeft}>
                      <TrendingUpIcon size={18} color="#10B981" />
                      <View>
                        <Text style={styles.commissionSource}>{c.source_user || 'Referral Bonus'}</Text>
                        <Text style={styles.commissionDate}>
                          {new Date(c.created_at).toLocaleDateString()}
                        </Text>
                      </View>
                    </View>
                    <Text style={styles.commissionAmount}>+${Number(c.amount).toFixed(2)}</Text>
                  </View>
                ))
              ) : (
                <View style={styles.emptyHistory}>
                  <AwardIcon size={32} color="#64748B" />
                  <Text style={styles.emptyTitle}>No Commissions Yet</Text>
                  <Text style={styles.emptySub}>
                    Share your referral link with friends to earn your first commission!
                  </Text>
                </View>
              )}
            </View>
          </View>
        )}
      </ScrollView>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0F172A',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingBottom: 16,
    backgroundColor: '#1E293B',
    borderBottomWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  backBtn: {
    padding: 8,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
  },
  refreshBtn: {
    padding: 8,
    borderRadius: 12,
    backgroundColor: 'rgba(59, 130, 246, 0.15)',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  scrollContent: {
    padding: 20,
  },
  heroCard: {
    backgroundColor: 'rgba(30, 41, 59, 0.7)',
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: 'rgba(245, 158, 11, 0.3)',
    marginBottom: 20,
  },
  heroTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 8,
  },
  heroTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: '#FFFFFF',
    flex: 1,
  },
  heroSub: {
    fontSize: 13,
    color: '#94A3B8',
    lineHeight: 18,
    marginBottom: 20,
  },
  metricsRow: {
    flexDirection: 'row',
    gap: 14,
  },
  metricBox: {
    flex: 1,
    backgroundColor: '#0F172A',
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  metricValue: {
    fontSize: 20,
    fontWeight: '800',
    color: '#FFFFFF',
    marginVertical: 4,
  },
  metricLabel: {
    fontSize: 12,
    color: '#94A3B8',
  },
  loadingBox: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 14,
    color: '#94A3B8',
  },
  contentGrid: {
    gap: 20,
  },
  sectionCard: {
    backgroundColor: '#1E293B',
    borderRadius: 20,
    padding: 18,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 16,
  },
  codeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#0F172A',
    padding: 14,
    borderRadius: 14,
    marginBottom: 12,
  },
  codeTextContainer: {
    flex: 1,
  },
  codeLabel: {
    fontSize: 11,
    color: '#94A3B8',
    textTransform: 'uppercase',
  },
  codeValue: {
    fontSize: 18,
    fontWeight: '800',
    color: '#3B82F6',
    letterSpacing: 1,
  },
  copyBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#3B82F6',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 10,
  },
  copyBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  linkRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#0F172A',
    padding: 12,
    borderRadius: 14,
  },
  linkText: {
    fontSize: 12,
    color: '#94A3B8',
    flex: 1,
    marginRight: 10,
  },
  linkActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  iconBtn: {
    padding: 10,
    borderRadius: 10,
    backgroundColor: 'rgba(59, 130, 246, 0.15)',
  },
  shareBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#10B981',
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 10,
  },
  shareBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  commissionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.05)',
  },
  commissionLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  commissionSource: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  commissionDate: {
    fontSize: 11,
    color: '#94A3B8',
  },
  commissionAmount: {
    fontSize: 14,
    fontWeight: '700',
    color: '#34D399',
  },
  emptyHistory: {
    alignItems: 'center',
    paddingVertical: 30,
  },
  emptyTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#FFFFFF',
    marginTop: 10,
    marginBottom: 4,
  },
  emptySub: {
    fontSize: 12,
    color: '#94A3B8',
    textAlign: 'center',
  },
});
